1) implement Spring boot, added entities and connected with it app le…
AntonPanchishko/BankService pull request #1
Opened 2021-02-28 19:04 UTC by AntonPanchishko

…vels

2021-02-28 23:44 UTC, vicire requested changes

2021-02-28 23:44 UTC, vicire commented on src/main/java/com/example/bankservicedemo/service/impl/RoleServiceImpl.java
> +        return roleRepository.getByRoleName(Role.RoleType.valueOf(name)).get();
What happened if the name of the role doesn`t exist in DB?

2021-02-28 23:44 UTC, vicire commented on src/main/java/com/example/bankservicedemo/service/impl/UserServiceImpl.java
> +        return userRepository.findById(id).get();
Same here

2021-02-28 23:44 UTC, vicire commented on src/main/java/com/example/bankservicedemo/service/impl/UserServiceImpl.java
> +        return userRepository.getFirstByPhoneNumber(phone).get();
and here

2021-03-01 08:44 UTC, vicire approved these changes

2021-03-01 09:41 UTC, boroda4436 requested changes

2021-03-01 09:41 UTC, boroda4436 commented on src/main/java/com/example/bankservicedemo/repository/UserRepository.java
> +    @Override
Do we need `@Override` annotation here?

2021-03-01 09:41 UTC, boroda4436 commented on src/main/java/com/example/bankservicedemo/repository/UserRepository.java
> +    Optional<User> findById(Long id);
Should we override the base method?

2021-03-01 09:41 UTC, boroda4436 commented on src/main/java/com/example/bankservicedemo/service/impl/RoleServiceImpl.java
> +                        new NoSuchElementException("Can't find role with such name " + name));
better throw your custom `NoSuchEntityException`

2021-03-01 09:41 UTC, boroda4436 commented on src/test/java/com/example/bankservicedemo/BankServiceDemoApplicationTests.java
> +import static org.junit.jupiter.api.Assertions.assertTrue;
Are you using this method?

2021-03-01 13:35 UTC, boroda4436 approved these changes

2021-03-01 20:17 UTC, merged