10) added new model and connected with it app levels
AntonPanchishko/BankService pull request #2
Opened 2021-03-01 20:18 UTC by AntonPanchishko

2021-03-01 20:32 UTC, YuraBondarenko approved these changes

2021-03-01 20:32 UTC, YuraBondarenko commented on src/main/java/com/example/bankservicedemo/model/Transaction.java
> +    private Account accountTo;
rename this columns for the table

2021-03-02 05:33 UTC, boroda4436 requested changes

2021-03-02 05:33 UTC, boroda4436 commented on src/main/java/com/example/bankservicedemo/model/Account.java
> +    private double balance;
```suggestion
    private BigDecimal balance;
```
please use BigDecimal for money fields

2021-03-02 05:33 UTC, boroda4436 commented on src/main/java/com/example/bankservicedemo/model/Transaction.java
> +    private double amount;
BigDecimal

2021-03-02 15:49 UTC, KseniiaMakarova requested changes

2021-03-02 15:49 UTC, KseniiaMakarova commented on pom.xml
> +            <artifactId>json-path</artifactId>
do you use this at this point?

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/model/Transaction.java
> +    @OneToOne
why OneToOne?

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/model/Transaction.java
> +    @OneToOne
same

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/repository/AccountRepository.java
> +    Account findByAccountNumber(String accountNumber);
```suggestion
    Optional<Account> findByAccountNumber(String accountNumber);
```

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/repository/TransactionRepository.java
> +            + " JOIN FETCH t.accountTo at"
is it obligatory to use join fetch here?

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/repository/AccountRepository.java
> +    @Query("SELECT a FROM accounts a JOIN FETCH a.user u WHERE u.phoneNumber = :phone")
same - try this
```suggestion
    @Query("SELECT a FROM accounts a WHERE a.user.phoneNumber = :phone")
```

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/AccountService.java
> +    void blockAccount(String accountNumber);
let's set `active` to false somewhere in controller and then just call `service.save()` - what do you think?

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/TransactionServiceImpl.java
> +    public void transfer(String fromAccount, String toAccount, int amount) {
```suggestion
    public void transfer(Account fromAccount, Account toAccount, int amount) {
```
and maybe we could move this to AccountService - how do you think?

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/TransactionServiceImpl.java
> +                .getAmount().subtract(BigDecimal.valueOf(amount)))) <= 0) {
what will be the value of `transactionOutcoming.getAmount()` here?
you created the empty object 2 lines ago

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/TransactionServiceImpl.java
> +        Account toAccountNyNumber = accountService.getByAccountNumber(toAccount);
```suggestion
        Account toAccountByNumber = accountService.getByAccountNumber(toAccount);
```

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/TransactionServiceImpl.java
> +    @Override
let's use the `@Transactional` annotation to make this whole logic in this method be executed in a single transaction
see this article https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/transaction/annotation/Transactional.html

2021-03-02 15:49 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/TransactionServiceImpl.java
> +                .getAccountNumber(), sortedByDateAndId);
```suggestion
        return transactionRepository.findAllByAccount(account, sortedByDateAndId);
```

2021-03-02 17:57 UTC, KseniiaMakarova requested changes

2021-03-02 17:57 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/controller/DataInsert.java
>      @PostConstruct
maybe let's remove @PostConstruct?

2021-03-02 17:57 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/AccountServiceImpl.java
>      @Override
let's remove blockAccount() method if we don't use it

2021-03-02 17:57 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/service/impl/TransactionServiceImpl.java
> +import javax.transaction.Transactional;
use org.springframework.transaction.annotation.Transactional

2021-03-02 17:57 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/repository/TransactionRepository.java
> +            + " t.accountFrom = :accountNumber")
can Account be equal to String?

2021-03-02 17:57 UTC, KseniiaMakarova commented on src/main/java/com/example/bankservicedemo/repository/TransactionRepository.java
>      List<Transaction> findAllByAccount(String accountNumber, Pageable sortedByDateAndId);
try `List<Transaction> findAllByAccount(String account, Pageable sortedByDateAndId);`

2021-03-03 08:26 UTC, KseniiaMakarova approved these changes
good job)

2021-03-03 09:36 UTC, merged